import dotenv from 'dotenv';

dotenv.config();

export const {
  PORT,
  AWS_S3_REGION,
  AWS_S3_BUCKET,
  AWS_S3_ACCESS_KEY_ID,
  AWS_S3_SECRET_ACCESS_KEY,
  AWS_ECS_CLUSTER,
  AWS_ECS_TASK,
  KAFKA_BROKER,
  KAFKA_USER,
  KAFKA_PASSWORD,
  AWS_ECS_REGION,
  AWS_ECS_ACCESS_KEY_ID,
  AWS_ECS_SECRET_ACCESS_KEY,
  CLICKHOUSE_URL,
  CLICKHOUSE_DB,
  CLICKHOUSE_USER,
  CLICKHOUSE_PASSWORD,
} = process.env;
